# Generated by Django 4.0 on 2021-12-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(db_index=True, max_length=20, verbose_name='Фамилия')),
                ('first_name', models.CharField(db_index=True, max_length=20, verbose_name='Имя')),
                ('mid_name', models.CharField(db_index=True, max_length=20, verbose_name='Отчество')),
                ('num_ser_pass', models.IntegerField(db_index=True, verbose_name='Серия и номер паспорта')),
                ('inn', models.IntegerField(db_index=True, verbose_name='ИНН')),
                ('birth_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата рождения')),
                ('position', models.CharField(db_index=True, max_length=50, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата окончания')),
                ('volume', models.FloatField(verbose_name='Объем финансирования')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['name'],
            },
        ),
    ]
